set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(UUSB_TOOLCHAIN_PREFIX arm-none-eabi CACHE STRING "GNU Arm Embedded prefix")

find_program(CMAKE_C_COMPILER NAMES ${UUSB_TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(CMAKE_AR NAMES ${UUSB_TOOLCHAIN_PREFIX}-gcc-ar REQUIRED)
find_program(CMAKE_RANLIB NAMES ${UUSB_TOOLCHAIN_PREFIX}-gcc-ranlib REQUIRED)
find_program(CMAKE_OBJCOPY NAMES ${UUSB_TOOLCHAIN_PREFIX}-objcopy REQUIRED)
find_program(CMAKE_OBJDUMP NAMES ${UUSB_TOOLCHAIN_PREFIX}-objdump REQUIRED)
find_program(CMAKE_SIZE NAMES ${UUSB_TOOLCHAIN_PREFIX}-size REQUIRED)
set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-m3 -mthumb")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-mcpu=cortex-m3 -mthumb")
